name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        IMAGE_NAME: my-image-name
        TAG: $(date +'%Y-%m-%d')
        TAG2: test2
        TAG3: 'test3'
      run: docker build . --file Dockerfile --tag $MATRIX_CONTEXT:$TAG --tag $MATRIX_CONTEXT:$TAG2 --tag $MATRIX_CONTEXT:$TAG3
